name: Benchmark

on:
  push:
    paths:
      - 'lib/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'test/scripts/**'

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['10.x', '12.x', '14.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-npm-cache
      - name: Install dependencies
        run: npm install --silent
      - name: Running benchmark
        run: node test/benchmark.js
